name: Build and push Docker image

on:
  push:
    tags:
      - v*
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Convert repository name
        id: kebab_case
#        run: echo ${{ github.repository }} | sed 's/^.*\///' | sed -r 's/(^|[^a-zA-Z0-9])([A-Z])/\1\l\2/g; s/[A-Z]/-\l&/g; s/^/kebab_repository=/' >> $GITHUB_OUTPUT
        run: echo ${{ github.repository }} | sed -r 's/[A-Z]/\l&/g; s/^/kebab_repository=/' >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ steps.kebab_case.outputs.kebab_repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}

      - name: Update Kubernetes manifests with new image tag
        run: |
          NEW_TAG=$(echo ${{ steps.meta.outputs.tags }} | awk -F ',' '{print $1}') # Assuming the first tag is the one you want
          sed -i 's|ghcr.io/${{ steps.kebab_case.outputs.kebab_repository }}:.*|ghcr.io/${{ steps.kebab_case.outputs.kebab_repository }}:$NEW_TAG|g' k8s/k8s-deployment.yml
        
      - name: Commit and push changes
        run: |
          git config --local user.email "ryuzu1006@gmail.com"
          git config --local user.name "${{ github.repository_owner }}"
          git add k8s/k8s-deployment.yaml
          git commit -m "Update image tag to $NEW_TAG"
          git push
        
        